// Array de objetos que guardan algunos patrones de conway, indicando nombre..
// tamaño minimo para que el patron funcione correctamente, y las coordenadas de las celdas vecinas para dibujar el patron

export const patterns = [
  {
    id: "1",
    type: "none",
    name: "Dot",
    image: "./images/dot.png",
    minRows: 1,
    minCols: 1,
    pattern: [[0, 0]],
  },

  {
    id: "2",
    name: "Blinker",
    type: "Oscillators",
    image: "./images/blinker.png",
    minRows: 3,
    minCols: 3,
    pattern: [
      [-1, 0],
      [0, 0],
      [1, 0],
    ],
  },

  {
    id: "3",
    name: "Toad",
    type: "Oscillators",
    image: "./images/toad.png",
    minRows: 4,
    minCols: 4,
    pattern: [
      [0, 0],
      [-1, 0],
      [0, -1],
      [-1, 1],
      [0, 1],
      [-1, 2],
    ],
  },

  {
    id: "4",
    name: "Beacon",
    type: "Oscillators",
    image: "./images/beacon.png",
    minRows: 4,
    minCols: 4,
    pattern: [
      [0, 0],
      [-1, 0],
      [0, -1],
      [-1, -1],
      [1, 1],
      [1, 2],
      [2, 1],
      [2, 2],
    ],
  },

  {
    id: "5",
    name: "Pulsar",
    type: "Oscillators",
    image: "./images/pulsar.png",
    minRows: 15,
    minCols: 15,
    pattern: [
      [1, 2],
      [1, 3],
      [1, 4],
      [2, 1],
      [3, 1],
      [4, 1],
      [2, 6],
      [3, 6],
      [4, 6],
      [6, 2],
      [6, 3],
      [6, 4],
      [2, -1],
      [3, -1],
      [4, -1],
      [2, -6],
      [3, -6],
      [4, -6],
      [1, -2],
      [1, -3],
      [1, -4],
      [6, -2],
      [6, -3],
      [6, -4],
      [-1, 2],
      [-1, 3],
      [-1, 4],
      [-1, -2],
      [-1, -3],
      [-1, -4],
      [-2, 1],
      [-3, 1],
      [-4, 1],
      [-2, -1],
      [-3, -1],
      [-4, -1],
      [-2, -6],
      [-3, -6],
      [-4, -6],
      [-2, 6],
      [-3, 6],
      [-4, 6],
      [-6, 2],
      [-6, 3],
      [-6, 4],
      [-6, -2],
      [-6, -3],
      [-6, -4],
    ],
  },

  {
    id: "6",
    name: "Pentadecathlon",
    type: "Oscillators",
    image: "./images/pentadecathlon.png",
    minRows: 16,
    minCols: 9,
    pattern: [
      [0, 0],
      [2, 0],
      [1, 0],
      [-3, 0],
      [-4, 0],
      [-1, 0],
      [-2, -1],
      [-2, 1],
      [3, -1],
      [3, 1],
      [4, 0],
      [5, 0],
    ],
  },

  {
    id: "7",
    name: "Glider",
    type: "Spaceships",
    image: "./images/glider.png",
    minRows: 5,
    minCols: 5,
    pattern: [
      [1, 0],
      [1, 1],
      [0, 1],
      [0, -1],
      [-1, 1],
    ],
  },

  {
    id: "8",
    name: "Lightweight spaceship",
    type: "Spaceships",
    image: "./images/LWSS.png",
    minRows: 6,
    minCols: 7,
    pattern: [
      [2, -1],
      [2, 0],
      [2, 1],
      [2, 2],
      [1, 2],
      [1, -2],
      [0, 2],
      [-1, 1],
      [-1, -2],
    ],
  },

  {
    id: "9",
    name: "Middleweight spaceship",
    type: "Spaceships",
    image: "./images/MWSS.png",
    minRows: 7,
    minCols: 9,
    pattern: [
      [2, -1],
      [2, 0],
      [2, 1],
      [2, 2],
      [2, 3],
      [1, -2],
      [1, 3],
      [0, 3],
      [-1, -2],
      [-1, 2],
      [-2, 0],
    ],
  },

  {
    id: "10",
    name: "Heavyweight spaceship",
    type: "Spaceships",
    image: "./images/HWSS.png",
    minRows: 7,
    minCols: 10,
    pattern: [
      [2, -1],
      [2, 0],
      [2, 1],
      [2, 2],
      [2, 3],
      [2, 4],
      [1, -2],
      [1, 4],
      [0, 4],
      [-1, -2],
      [-1, 3],
      [-2, 0],
      [-2, 1],
    ],
  },

  {
    id: "11",
    name: "Block",
    type: "Still lifes",
    image: "./images/block.png",
    minRows: 2,
    minCols: 2,
    pattern: [
      [0, 0],
      [0, 1],
      [1, 0],
      [1, 1],
    ],
  },

  {
    id: "12",
    name: "Beehive",
    type: "Still lifes",
    image: "./images/beehive.png",
    minRows: 3,
    minCols: 4,
    pattern: [
      [-1, 0],
      [0, -1],
      [1, 0],
      [1, 1],
      [-1, 1],
      [0, 2],
    ],
  },

  {
    id: "13",
    name: "Loaf",
    type: "Still lifes",
    image: "./images/loaf.png",
    minRows: 4,
    minCols: 4,
    pattern: [
      [-1, 0],
      [-1, 1],
      [0, -1],
      [0, 2],
      [1, 0],
      [1, 2],
      [2, 1],
    ],
  },

  {
    id: "14",
    name: "Boat",
    type: "Still lifes",
    image: "./images/boat.png",
    minRows: 3,
    minCols: 3,
    pattern: [
      [-1, 0],
      [-1, -1],
      [0, -1],
      [0, 1],
      [1, 0],
    ],
  },

  {
    id: "15",
    name: "Tub",
    type: "Still lifes",
    image: "./images/tub.png",
    minRows: 3,
    minCols: 3,
    pattern: [
      [-1, 0],
      [0, -1],
      [0, 1],
      [1, 0],
    ],
  },
];
